# Default layout for work machine
# Creates: shell (20% left) | nvim (80% right)

windows:
  - name: main
    panes:
      - command: ""
      - split: horizontal
        size: 80%
        command: "nvim"
        focus: true
