# Default layout template
# Creates: shell (20% left) | nvim (80% right)
#
# Layout format:
#   panes: list of pane definitions
#   Each pane has:
#     - split: horizontal (left|right) or vertical (top|bottom)
#     - size: percentage of the split (for the NEW pane)
#     - target: which pane to split (0-indexed, optional, defaults to last created)
#     - command: command to run after all panes are created
#     - focus: true to focus this pane at the end

windows:
  - name: main
    panes:
      - command: ""
      - split: horizontal
        size: 80%
        command: "nvim"
        focus: true
